
static char bngpiodir_ok      = zero;
static int  chip_fd;
static char program           = zero;
static char program_ix        = zero;
static char opcode            = LOOP;
static char overspeed         = one;
static int  old_btn_bits      = zero;
static int  old_led_bits      = zero;
static int  problem           = zero;

typedef struct
{
  char   pin;
  char   val;
  char   out;
  int    weight;
} bn_gpio_line;

typedef struct
{
  char   num;
  char   colrs;                              // 0, 1, 2 or 3
  char   actv;
  bn_gpio_line *red;
  bn_gpio_line *grn;
  bn_gpio_line *blu;
} bn_gpio_led;

typedef struct
{
  char   num;
  char   actv;
  bn_gpio_line *hot;
} bn_gpio_btn;

typedef struct {
  bn_gpio_led *led0;
  bn_gpio_led *led1;
  bn_gpio_led *led2;
  bn_gpio_led *led3;
  bn_gpio_btn *btn0;
  bn_gpio_btn *btn1;
  bn_gpio_btn *btn2;
  int    line_count;
  int    curr_weight;
  int    read_mask;
  int    write_mask;
  bn_gpio_line  *offsets[12];
  // bn_gpio_line  (*offsets)[13];
  // bn_gpio_line** offsets;
  // char (*list)[12]
} bn_gpio_config;

/* thread data struct of values needed by reader thread */
typedef struct {
  struct gpio_v2_line_config *linecfg;
  struct gpio_v2_line_request *linereq;
  struct gpio_v2_line_values *linevals;
  int fd;
} gpio_v2_t;

static bn_gpio_line led0red   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led0grn   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led0blu   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led1red   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led1grn   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led1blu   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led2red   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led2grn   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led2blu   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led3red   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led3grn   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line led3blu   = { .pin = 0, .val = 0, .weight = 0, .out = 1 };
static bn_gpio_line btn0hot   = { .pin = 0, .val = 2, .weight = 0, .out = 0 };
static bn_gpio_line btn1hot   = { .pin = 0, .val = 2, .weight = 0, .out = 0 };
static bn_gpio_line btn2hot   = { .pin = 0, .val = 2, .weight = 0, .out = 0 };
static bn_gpio_led led0       = { .num = 0, .colrs = 0, .actv = 0, .red = &led0red, .grn = &led0grn, .blu = &led0blu };
static bn_gpio_led led1       = { .num = 1, .colrs = 0, .actv = 0, .red = &led1red, .grn = &led1grn, .blu = &led1blu };
static bn_gpio_led led2       = { .num = 2, .colrs = 0, .actv = 0, .red = &led2red, .grn = &led2grn, .blu = &led2blu };
static bn_gpio_led led3       = { .num = 3, .colrs = 0, .actv = 0, .red = &led3red, .grn = &led3grn, .blu = &led3blu };
static bn_gpio_btn btn0       = { .num = 0, .actv = 0, .hot = &btn0hot };
static bn_gpio_btn btn1       = { .num = 1, .actv = 0, .hot = &btn1hot };
static bn_gpio_btn btn2       = { .num = 2, .actv = 0, .hot = &btn2hot };
static bn_gpio_led* leds[4]   = { &led0 , &led1 , &led2 , &led3 };
static bn_gpio_btn* btns[3]   = { &btn0 , &btn1 , &btn2 };

static bn_gpio_config config  =  {
                                  .led0  = &led0,
                                  .led1  = &led1,
                                  .led2  = &led2,
                                  .led3  = &led3,
                                  .btn0  = &btn0,
                                  .btn1  = &btn1,
                                  .btn2  = &btn2,
                                  .line_count       = 0,
                                  .curr_weight      = 0,
                                  .read_mask        = 0,
                                  .write_mask       = 0
                                };

#if VERBOSE == 5
static char pattrns[8][24]    = {
                              //  ~   ~    ~     ~      ~       ~        ~         ~          ~           ~            ~             ~
                              // The pattern is set at initialization
                              // 
                              // There are eight patterns, 0 - 7
                              // If a pattern 8 is shown or entered, it means pattern 0
                              // 
                              // 
                              // ABOUT PATT1 (AND PATT0)
                              // 
                              // 2 LEDs 1 BTN B      https://www.button.network/gpio-guide/pinout/buttonnet21c.html
                              // It uses narrow grouping and follows the order ground-red-green-blue for both LEDs.
                              // This is for the prototype; the button placement, particularly, may change
                              // Addendum:  I added a BTN on 17, please note that this will require an entry in config.txt
                              // https://forums.raspberrypi.com/viewtopic.php?f=117&t=208748
                              // 
                              // gpio=17=pu
                              // 
                              //  PATT0: LED1, LED2 and BTN0      (requires 'gpio=17=pu' in config.txt)                buttonnet21c.html
                              //        ~  ~  ~   LED-0   ~  ~  ~       ~  ~  ~   LED-1   ~  ~  ~       ~  ~  ~   LED-2   ~  ~  ~       ~  ~  ~   LED-3   ~  ~  ~     BTN-0   BTN-1   BTN-2  empty
                              //        R       G       B       W       R       G       B       W       R       G       B       W       R       G       B       W
                                  {     17 ,    27 ,    22 ,    22 ,    25 ,     8 ,     7 ,     7 ,    11 ,     9 ,    10 ,    10 ,     6 ,    16 ,    26 ,    26 ,    17 ,     4 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 },
                                  {      0 ,     0 ,     0 ,     0 ,     1 ,     1 ,     1 ,     0 ,     1 ,     1 ,     1 ,     0 ,     0 ,     0 ,     0 ,     0 ,     1 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 },
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29 
                              // 
                              //       (same as PATT0)
                              //  PATT1: LED1, LED2 and BTN0      (requires 'gpio=17=pu' in config.txt)                buttonnet21c.html
                              //        ~  ~  ~   LED-0   ~  ~  ~       ~  ~  ~   LED-1   ~  ~  ~       ~  ~  ~   LED-2   ~  ~  ~       ~  ~  ~   LED-3   ~  ~  ~     BTN-0   BTN-1   BTN-2  empty
                              //        R       G       B       W       R       G       B       W       R       G       B       W       R       G       B       W
                                  {     17 ,    27 ,    22 ,    22 ,    25 ,     8 ,     7 ,     7 ,    11 ,     9 ,    10 ,    10 ,     6 ,    16 ,    26 ,    26 ,    17 ,     4 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 },
                                  {      0 ,     0 ,     0 ,     0 ,     1 ,     1 ,     1 ,     0 ,     1 ,     1 ,     1 ,     0 ,     0 ,     0 ,     0 ,     0 ,     1 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 }
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29 
                              // 
                                };
#endif

static char progs[ 80][80]    = {

                              // PROGRAM ZERO                      PROGRAM ZERO  
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM ONE                       PROGRAM ONE  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   REDD ,  REDD ,  REDD ,  REDD ,  GREN ,  GREN ,  GREN ,  GREN ,  BLUE ,  BLUE ,  BLUE ,  BLUE ,  REDD ,  REDD ,  REDD ,  REDD ,  GREN ,  GREN ,  GREN ,  GREN ,  BLUE ,  BLUE ,  BLUE ,  BLUE ,  REDD ,  REDD ,  REDD ,  REDD ,  GREN ,  GREN ,  GREN ,  GREN ,  BLUE ,  BLUE ,  BLUE ,  BLUE ,  REDD ,  REDD ,  REDD ,  REDD ,  GREN ,  GREN ,  GREN ,  GREN ,  BLUE ,  BLUE ,  BLUE ,  BLUE ,  REDD ,  REDD ,  REDD ,  REDD ,  GREN ,  GREN ,  GREN ,  GREN ,  BLUE ,  BLUE ,  BLUE ,  BLUE ,  REDD ,  REDD ,  REDD ,  REDD ,  GREN ,  GREN ,  GREN ,  GREN ,  BLUE ,  BLUE ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM TWO                       PROGRAM TWO  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM THREE                     PROGRAM THREE  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM FOUR                      PROGRAM FOUR             Pointed upstream
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM FIVE                      PROGRAM FIVE             Connected upstream
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  MGNT ,  MGNT ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM SIX                       PROGRAM SIX              Pointed dnstream
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM SEVEN                     PROGRAM SEVEN            Connected dnstream
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  GREN ,  GREN ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM EIGHT                     PROGRAM EIGHT  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM NINE                      PROGRAM NINE  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM TEN                       PROGRAM TEN  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU ,  LOOP , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  CYAN ,  CYAN ,  MGNT ,  MGNT ,  YELW ,  YELW ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,  REDD ,  REDD ,  GREN ,  GREN ,  BLUE ,  BLUE ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM ELEVEN                    PROGRAM ELEVEN  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM TWELVE                    PROGRAM TWELVE  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM THIRTEEN                  PROGRAM THIRTEEN  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM FOURTEEN                  PROGRAM FOURTEEN  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 

                              // PROGRAM FIFTEEN                   PROGRAM FIFTEEN  
                                  {  CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU , CNTNU } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {      0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 ,     0 } ,
                                  {   OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF ,  OFFF } 
                              //        0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      33      34      35      36      37      38      39      40      41      42      43      44      45      46      47      48      49      50      51      52      53      54      55      56      57      58      59      60      61      62      63      64      65      66      67      68      69      70      71      72      73      74      75      76      77      78      79 
                                };

//  ~   ~    ~     ~      ~       ~        ~         ~          ~           ~            ~             ~
// 

static char b36ins[128]       = {     36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,
                                      36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,     0 ,     1 ,     2 ,     3 ,     4 ,     5 ,     6 ,     7 ,     8 ,     9 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    10 ,    11 ,    12 ,    13 ,    14 ,    15 ,    16 ,    17 ,    18 ,    19 ,    20 ,    21 ,    22 ,    23 ,    24 ,
                                      25 ,    26 ,    27 ,    28 ,    29 ,    30 ,    31 ,    32 ,    33 ,    34 ,    35 ,    36 ,    36 ,    36 ,    36 ,    36 ,    36 ,    10 ,    11 ,    12 ,    13 ,    14 ,    15 ,    16 ,    17 ,    18 ,    19 ,    20 ,    21 ,    22 ,    23 ,    24 ,    25 ,    26 ,    27 ,    28 ,    29 ,    30 ,    31 ,    32 ,
                                      33 ,    34 ,    35 ,    36 ,    36 ,    36 ,    36 ,    36 };
// static char b36outs[36]       = {     48 ,    49 ,    50 ,    51 ,    52 ,    53 ,    54 ,    55 ,    56 ,    57 ,    97 ,    98 ,    99 ,   100 ,   101 ,   102 ,   103 ,   104 ,   105 ,   106 ,   107 ,   108 ,   109 ,   110 ,   111 ,   112 ,   113 ,   114 ,   115 ,   116 ,   117 ,   118 ,   119 ,   120 ,   121 ,   122 };
// static char bngpiodir[13]     = {     47 ,   101 ,   116 ,    99 ,    47 ,    98 ,   110 ,    47 ,   103 ,   112 ,   105 ,   111 ,    47 };
static char bngpiodir[15]     = {     47 ,   101 ,   116 ,    99 ,    47 ,   112 ,   108 ,   101 ,    98 ,    47 ,   103 ,   112 ,   105 ,   111 ,    47 };
static char pwr2[8]           = {      1 ,     2 ,     4 ,     8 ,    16 ,    32 ,    64 ,   128 };

