.TH HELLODEB 1 "21 February 2025" "plebgpio"
.SH NAME
plebgpio \- print pleb gpio
.SH SYNOPSIS
plebgpio
.SH DESCRIPTION
plebgpio manipulate buttons and leds on rpi gpio
.SH OPTIONS
plebgpio does not take any options
.SH SEE ALSO
dpkg-buildpackage(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Brian Button (bb@buttonnet.com)
